# Homebrew formula for blemees-tui.
#
# This file is a *stub* meant to be copied into the dedicated tap repo
# (`blemees/homebrew-tap`) once the project publishes a versioned release
# on PyPI. The placeholders marked `TODO` get filled in by the tap's
# release automation (or by hand for the first release).
#
# Once landed in the tap, users install with:
#
#     brew install blemees/tap/blemees-tui
#
# To regenerate the formula's Python resource list after a dependency
# bump, run inside this repo:
#
#     pipx install homebrew-pypi-poet
#     poet -f blemees-tui >> blemees-tui.rb
#
# and copy the emitted `resource` blocks into the formula below.

class BlemeesTui < Formula
  include Language::Python::Virtualenv

  desc "Multi-session terminal chat for blemeesd (Claude Code + Codex)"
  homepage "https://github.com/blemees/blemees-tui"
  # TODO: replace with the actual PyPI release URL + sha256 once published.
  url "https://files.pythonhosted.org/packages/source/b/blemees-tui/blemees_tui-0.1.0.tar.gz"
  sha256 "TODO_REPLACE_WITH_PYPI_TARBALL_SHA256"
  license "MIT"

  depends_on "python@3.13"

  # TODO: append `resource "..."` blocks generated by `poet -f blemees-tui`.
  # Required runtime deps (verbatim from pyproject.toml):
  #   - blemees>=0.9.0
  #   - textual>=0.80
  # Plus their transitive closures.

  def install
    virtualenv_install_with_resources
  end

  test do
    # Smoke test: the binary should at least respond to --help without
    # needing a live blemeesd socket.
    assert_match "blemees", shell_output("#{bin}/blemees --help")
  end
end
